name: CI-Snapshot
on:
  push:
    tags:
      - SNAPSHOT-*

jobs:
  publish-snapshot-sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d '-' -f 2)
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: assemble publish -PossrhUsername=${{secrets.SONATYPE_NEXUS_USERNAME}} -PossrhPassword=${{secrets.SONATYPE_NEXUS_PASSWORD}}
      - name: Create Snapshot Release in Github
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}-SNAPSHOT
          release_name: ${{ steps.get_version.outputs.VERSION }}-SNAPSHOT
          body: |
            Available in Sonatype SNAPSHOTs repository under:
            `io.reactiverse:aws-sdk:${{ steps.get_version.outputs.VERSION }}-SNAPSHOT`
          draft: true
          prerelease: true
